insert into users ("firstName", "lastName", "email", "phoneNumber", "password") values ('Maude', 'Jerosch', 'mjerosch0@dmoz.org', '1893739042', 'hAPblq');
insert into users ("firstName", "lastName", "email", "phoneNumber", "password") values ('Ax', 'Besson', 'abesson1@marriott.com', '6125051825', '4P2JXxiM');
insert into users ("firstName", "lastName", "email", "phoneNumber", "password") values ('Westley', 'Buckberry', 'wbuckberry2@home.pl', '5399421065', 'LqdgeLPtHi');
insert into users ("firstName", "lastName", "email", "phoneNumber", "password") values ('Hussein', 'Parkyn', 'hparkyn3@about.me', '9428460062', 'xF2KHQU2D');
insert into users ("firstName", "lastName", "email", "phoneNumber", "password") values ('Odilia', 'Cumberpatch', 'ocumberpatch4@addtoany.com', '4892501180', '5bbku41P9');
insert into users ("firstName", "lastName", "email", "phoneNumber", "password") values ('Esme', 'Brandacci', 'ebrandacci5@mayoclinic.com', '1058808922', 'gX2PmMLW');
insert into users ("firstName", "lastName", "email", "phoneNumber", "password") values ('Reed', 'Camsey', 'rcamsey6@ehow.com', '6671421159', '88gNzM');
insert into users ("firstName", "lastName", "email", "phoneNumber", "password") values ('Thomasa', 'Canland', 'tcanland7@google.com', '9532323611', 'tKVeqqR');
insert into users ("firstName", "lastName", "email", "phoneNumber", "password") values ('Ingrim', 'Dufour', 'idufour8@chronoengine.com', '1294643326', 'RGUEkWX');
insert into users ("firstName", "lastName", "email", "phoneNumber", "password") values ('Demott', 'Ruffy', 'druffy9@bloglovin.com', '4956139767', 'K2iwI7vzR');
insert into users ("firstName", "lastName", "email", "phoneNumber", "password") values ('Walker', 'Hofler', 'whoflera@bing.com', '2761962066', 'QGlvBhp');
insert into users ("firstName", "lastName", "email", "phoneNumber", "password") values ('Creigh', 'Gobat', 'cgobatb@independent.co.uk', '6186420511', 'MqCu80');
insert into users ("firstName", "lastName", "email", "phoneNumber", "password") values ('Vlad', 'Padson', 'vpadsonc@privacy.gov.au', '8277801917', 'Z4QHMkW');
insert into users ("firstName", "lastName", "email", "phoneNumber", "password") values ('Desmond', 'Beckingham', 'dbeckinghamd@issuu.com', '7439620704', 'zpRQbS19');
insert into users ("firstName", "lastName", "email", "phoneNumber", "password") values ('Shayne', 'Downgate', 'sdowngatee@example.com', '6466306646', 'd7dUB2oAe16x');
insert into users ("firstName", "lastName", "email", "phoneNumber", "password") values ('Burke', 'Dwelley', 'bdwelleyf@ustream.tv', '1307563339', 'oZhUT98');
insert into users ("firstName", "lastName", "email", "phoneNumber", "password") values ('Enid', 'Butchers', 'ebutchersg@purevolume.com', '8943529368', 'wNdQql4g3N5x');
insert into users ("firstName", "lastName", "email", "phoneNumber", "password") values ('Wernher', 'Du Fray', 'wdufrayh@abc.net.au', '4393970453', 'st84f6dtN4');
insert into users ("firstName", "lastName", "email", "phoneNumber", "password") values ('Fayina', 'Willcot', 'fwillcoti@51.la', '4421653201', 'UtWNpFrv2Gqt');
insert into users ("firstName", "lastName", "email", "phoneNumber", "password") values ('Lettie', 'Bescoby', 'lbescobyj@nasa.gov', '6279203231', 'uKJljSaEDDWi');

insert into products ("name", "description", "pathToImage", "price", "quantity") values ('Kawa Lavazza Orzo', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', 'http://dummyimage.com/400x400.png/ff4444/ffffff', 24.5, 7);
insert into products ("name", "description", "pathToImage", "price", "quantity") values ('Kawa Crème e Aroma', 'Donec ut mauris eget massa tempor convallis.', 'http://dummyimage.com/400x400.png/cc0000/ffffff', 43.5, 3);
insert into products ("name", "description", "pathToImage", "price", "quantity") values ('Kawa Starbucks', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 'http://dummyimage.com/400x400.png/ff4444/ffffff', 31, 6);
insert into products ("name", "description", "pathToImage", "price", "quantity") values ('Kawa Costa', 'In congue. Etiam justo.', 'http://dummyimage.com/400x400.png/5fa2dd/ffffff', 22.5, 4);
insert into products ("name", "description", "pathToImage", "price", "quantity") values ('Kawa Bulk Mocha', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 'http://dummyimage.com/400x400.png/ff4444/ffffff', 55, 7);
insert into products ("name", "description", "pathToImage", "price", "quantity") values ('Kawa Wietnamska Trung Nguyen', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'http://dummyimage.com/400x400.png/ff4444/ffffff', 56, 3);
insert into products ("name", "description", "pathToImage", "price", "quantity") values ('Kawa Pellini', 'Curabitur convallis.', 'http://dummyimage.com/400x400.png/5fa2dd/ffffff', 27, 6);
insert into products ("name", "description", "pathToImage", "price", "quantity") values ('Kawa Davidoff', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 'http://dummyimage.com/400x400.png/dddddd/000000', 38, 7);
insert into products ("name", "description", "pathToImage", "price", "quantity") values ('Kawa ziarnista BLUE ORCA COFFEE Brazilliana Toucano', 'In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 'http://dummyimage.com/400x400.png/cc0000/ffffff', 23, 4);
insert into products ("name", "description", "pathToImage", "price", "quantity") values ('Kawa Manufaktura Kawy', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 'http://dummyimage.com/400x400.png/ff4444/ffffff', 31.5, 6);
insert into products ("name", "description", "pathToImage", "price", "quantity") values ('Aromatyczny olejek CBD', 'Praesent id massa id nisl venenatis lacinia.', 'http://dummyimage.com/400x400.png/ff4444/ffffff', 23, 6);
insert into products ("name", "description", "pathToImage", "price", "quantity") values ('Susz konopny CBD Dr Joint', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', 'http://dummyimage.com/400x400.png/5fa2dd/ffffff', 55.5, 3);
insert into products ("name", "description", "pathToImage", "price", "quantity") values ('Olej CBD 20%', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'http://dummyimage.com/400x400.png/cc0000/ffffff', 56, 5);
insert into products ("name", "description", "pathToImage", "price", "quantity") values ('Miód z CBD', 'Nulla tellus.', 'http://dummyimage.com/400x400.png/5fa2dd/ffffff', 45.5, 7);
insert into products ("name", "description", "pathToImage", "price", "quantity") values ('Pre-Roll CBD Dr Joint', 'Curabitur at ipsum ac tellus semper interdum.', 'http://dummyimage.com/400x400.png/cc0000/ffffff', 42.5, 4);
insert into products ("name", "description", "pathToImage", "price", "quantity") values ('Saszetki CBD', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'http://dummyimage.com/400x400.png/ff4444/ffffff', 22.5, 5);
insert into products ("name", "description", "pathToImage", "price", "quantity") values ('Kawiarka Tchibo', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 'http://dummyimage.com/400x400.png/5fa2dd/ffffff', 51, 5);
insert into products ("name", "description", "pathToImage", "price", "quantity") values ('Herbata z kwiatów Okal', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'http://dummyimage.com/400x400.png/ff4444/ffffff', 37.5, 8);
insert into products ("name", "description", "pathToImage", "price", "quantity") values ('Herbata Wow Tea', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'http://dummyimage.com/400x400.png/5fa2dd/ffffff', 28, 3);
insert into products ("name", "description", "pathToImage", "price", "quantity") values ('Frenchpress zaparzacz do kawy i herbaty', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'http://dummyimage.com/400x400.png/5fa2dd/ffffff', 23.5, 7);

insert into discounts ("discountPercentage", "name", "endDate") values (15, 'Wiosenna obniżka', '2024-01-31 23:59:59');

insert into categories ("name", "description", "pathToImage", "parentId") values ('Kawa i herbata', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', 'http://dummyimage.com/400x400.png/ff4444/ffffff', null);
insert into categories ("name", "description", "pathToImage", "parentId") values ('Trawa', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', 'http://dummyimage.com/400x400.png/ff4400/00ffff', null);
insert into categories ("name", "description", "pathToImage", "parentId") values ('Kawa', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', 'http://dummyimage.com/400x400.png/224400/0033ff', 1);
insert into categories ("name", "description", "pathToImage", "parentId", "discountId") values ('Herbata', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', 'http://dummyimage.com/400x400.png/ff44aa/bbf77f', 1, 1);
insert into categories ("name", "description", "pathToImage", "parentId") values ('Akcesoria', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', 'http://dummyimage.com/400x400.png/22aa00/4433ff', 1);

insert into addresses ("street", "houseNumber", "flatNumber", "city", "country", "postCode") values ('Barby', 15, 48, 'Polańczyk', 'Poland', '38-610');
insert into addresses ("street", "houseNumber", "flatNumber", "city", "country", "postCode") values ('Longview', 13, null, 'Sawin', 'Poland', '22-107');
insert into addresses ("street", "houseNumber", "flatNumber", "city", "country", "postCode") values ('Hoffman', 18, null, 'Grodków', 'Poland', '49-200');
insert into addresses ("street", "houseNumber", "flatNumber", "city", "country", "postCode") values ('Cardinal', 28, null, 'Kowary', 'Poland', '58-530');
insert into addresses ("street", "houseNumber", "flatNumber", "city", "country", "postCode") values ('Dakota', 4, 44, 'Stepnica', 'Poland', '72-112');
insert into addresses ("street", "houseNumber", "flatNumber", "city", "country", "postCode") values ('Loomis', 23, 40, 'Psary', 'Poland', '32-546');
insert into addresses ("street", "houseNumber", "flatNumber", "city", "country", "postCode") values ('Huxley', 6, 1, 'Kortowo', 'Poland', '11-041');
insert into addresses ("street", "houseNumber", "flatNumber", "city", "country", "postCode") values ('Oxford', 28, 3, 'Mosty', 'Poland', '84-353');
insert into addresses ("street", "houseNumber", "flatNumber", "city", "country", "postCode") values ('1st', 25, null, 'Trzebinia', 'Poland', '32-541');
insert into addresses ("street", "houseNumber", "flatNumber", "city", "country", "postCode") values ('Meadow Valley', 22, null, 'Siemiątkowo', 'Poland', '09-135');
insert into addresses ("street", "houseNumber", "flatNumber", "city", "country", "postCode") values ('Express', 33, 60, 'Kokotów', 'Poland', '32-020');
insert into addresses ("street", "houseNumber", "flatNumber", "city", "country", "postCode") values ('Mendota', 15, 37, 'Cieplice Śląskie Zdrój', 'Poland', '58-588');
insert into addresses ("street", "houseNumber", "flatNumber", "city", "country", "postCode") values ('Bluejay', 19, 54, 'Pomiechówek', 'Poland', '05-180');
insert into addresses ("street", "houseNumber", "flatNumber", "city", "country", "postCode") values ('Shopko', 39, 19, 'Sieniawa', 'Poland', '37-530');
insert into addresses ("street", "houseNumber", "flatNumber", "city", "country", "postCode") values ('Saint Paul', 12, 47, 'Kętrzyn', 'Poland', '11-414');
insert into addresses ("street", "houseNumber", "flatNumber", "city", "country", "postCode") values ('Bunker Hill', 40, 62, 'Klonowa', 'Poland', '98-273');
insert into addresses ("street", "houseNumber", "flatNumber", "city", "country", "postCode") values ('Eastlawn', 20, 35, 'Nowa Sarzyna', 'Poland', '37-310');
insert into addresses ("street", "houseNumber", "flatNumber", "city", "country", "postCode") values ('Hanover', 10, 52, 'Przecław', 'Poland', '72-005');
insert into addresses ("street", "houseNumber", "flatNumber", "city", "country", "postCode") values ('Tennyson', 26, 5, 'Oborniki Śląskie', 'Poland', '55-120');
insert into addresses ("street", "houseNumber", "flatNumber", "city", "country", "postCode") values ('Vernon', 16, null, 'Pomiechówek', 'Poland', '05-180');

insert into category_products ("categoriesId", "productsId") values (3, 1);
insert into category_products ("categoriesId", "productsId") values (3, 2);
insert into category_products ("categoriesId", "productsId") values (3, 3);
insert into category_products ("categoriesId", "productsId") values (3, 4);
insert into category_products ("categoriesId", "productsId") values (3, 5);
insert into category_products ("categoriesId", "productsId") values (3, 6);
insert into category_products ("categoriesId", "productsId") values (3, 7);
insert into category_products ("categoriesId", "productsId") values (3, 8);
insert into category_products ("categoriesId", "productsId") values (3, 9);
insert into category_products ("categoriesId", "productsId") values (3, 10);

insert into category_products ("categoriesId", "productsId") values (2, 11);
insert into category_products ("categoriesId", "productsId") values (2, 12);
insert into category_products ("categoriesId", "productsId") values (2, 13);
insert into category_products ("categoriesId", "productsId") values (2, 14);
insert into category_products ("categoriesId", "productsId") values (2, 15);
insert into category_products ("categoriesId", "productsId") values (2, 16);

insert into category_products ("categoriesId", "productsId") values (4, 18);
insert into category_products ("categoriesId", "productsId") values (4, 19);

insert into category_products ("categoriesId", "productsId") values (5, 17);
insert into category_products ("categoriesId", "productsId") values (5, 20);
