export const REACT_APP_LOGIN_ENDPOINT = process.env.REACT_APP_BE_ADDRESS + "/auth/login"
export const REACT_APP_REGISTER_ENDPOINT = process.env.REACT_APP_BE_ADDRESS + "/auth/register"
export const REACT_APP_CATEGORIES_ENDPOINT = process.env.REACT_APP_BE_ADDRESS + "/categories"
export const REACT_APP_PRODUCTS_ENDPOINT = process.env.REACT_APP_BE_ADDRESS + "/products"
export const REACT_APP_ORDERS_ENDPOINT = process.env.REACT_APP_BE_ADDRESS + "/orders"
export const REACT_APP_POST_COMPLAINT_ENDPOINT = process.env.REACT_APP_BE_ADDRESS + "/complaints"